/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {

  docs: [
    {
      type: 'doc',
      label: 'Main Menu',
      id: 'intro'
    },
    {
      type: 'link',
      label: 'ESX-Legacy',
      href: '/docs/esx_legacy'
    },
    {
      type: 'link',
      label: 'Tebex Documentation',
      href: '/docs/category/global'
    },
    {
      type: 'link',
      label: 'supv_core',
      href: '/docs/supv_core'
    },
  ],
  esx_legacy: [
    {
      type: 'link',
      label: '← Retour',
      href: '/docs/intro',
    },
    {
      type: 'category',
      label: 'Esx-Legacy',
      link: {
        type: 'generated-index',
        title: 'ESX Legacy',
        description: 'Une documention en plus 👀',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'esx_legacy',
        },
      ],
    }
  ],
  tebex: [
    {
      type: 'link',
      label: '← Retour',
      href: '/docs/intro',
    },
    {
      type: 'category',
      label: 'Global',
      link: {
        type: 'generated-index',
        title: 'Tebex Documentation',
        description: 'Une documention en plus 👀',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'tebex_doc',
        },
      ],
    },
    {
      type: 'link',
      label: 'supv_oxitems',
      href: '/docs/supv_oxitems/main',
    },
  ],
  supv_oxitems: [
    {
      type: 'link',
      label: '← Retour',
      href: '../category/global',
    },
    {
      type: 'doc',
      label: 'Général',
      id: 'supv_oxitems/main',
    },
    {
      type: 'category',
      label: 'Handcuff system',
      link: {
        type: 'generated-index',
        title: 'supv_oxitems',
        description: 'Une documention en plus 👀',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'supv_oxitems/developpement',
        },
      ],
    },
    {
      type: 'category',
      label: 'Carkey system',
      link: {
        type: 'generated-index',
        title: 'supv_oxitems',
        description: 'Une documention en plus 👀',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'supv_oxitems/carkey',
        },
      ],
    }
  ],
  supv_core: [
    {
      type: 'link',
      label: '← Retour',
      href: '/docs/intro',
    },
    {
      type: 'category',
      label: 'supv_core',
      link: {
        type: 'generated-index',
        title: 'supv_core',
        description: 'Une documention en plus 👀',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'supv_core',
        },
      ],
    }
  ]
};

module.exports = sidebars;
