/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {

  docs: [
    {
      type: 'doc',
      label: 'Main Menu',
      id: 'intro'
    },
    {
      type: 'link',
      label: 'ESX-Legacy',
      href: '/docs/esx_legacy'
    }
  ],
  esx_legacy: [
    {
      type: 'link',
      label: '← Retour',
      href: '/docs/intro',
    },
    {
      type: 'category',
      label: 'Esx-Legacy',
      link: {
        type: 'generated-index',
        title: 'ESX Legacy',
        description: 'Une documention en plus 👀',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'esx_legacy',
        },
      ],
    }
  ]
};

module.exports = sidebars;
